name: flutter_cache_manager
description: Generic cache manager for flutter. Saves web files on the storages of the device and saves the cache info using sqflite.
version: 3.1.1
homepage: https://github.com/Baseflow/flutter_cache_manager

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  clock: ^1.0.1
  collection: ^1.14.13
  file: ^6.0.0-nullsafety.1
  flutter:
    sdk: flutter
  http: ^0.12.2
  image: ^2.1.19
  path: ^1.7.0
  path_provider: ^1.6.28
  pedantic: ^1.9.2
  rxdart: ^0.25.0
  sqflite: ^1.3.2+3
  uuid: ^2.2.2
